# Generated by Django 6.0.5 on 2026-05-19 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='albums/')),
                ('tracksCount', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='artists/')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('path', models.FileField(upload_to='tracks/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.album')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.artist')),
            ],
            options={
                'unique_together': {('album', 'artist')},
            },
        ),
        migrations.CreateModel(
            name='TrackAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.artist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.track')),
            ],
            options={
                'unique_together': {('track', 'artist')},
            },
        ),
    ]
