# Generated by Django 6.0.5 on 2026-05-21 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_favoritetrack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumauthor',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='app.album'),
        ),
        migrations.AlterField(
            model_name='albumauthor',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='app.artist'),
        ),
        migrations.AlterField(
            model_name='favoritetrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_by', to='app.track', verbose_name='Трек'),
        ),
        migrations.AlterField(
            model_name='favoritetrack',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_tracks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='app.album'),
        ),
        migrations.AlterField(
            model_name='trackauthor',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='app.artist'),
        ),
        migrations.AlterField(
            model_name='trackauthor',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='app.track'),
        ),
    ]
