# Generated by Django 6.0.5 on 2026-05-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_album_slug_track_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='albums/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='artists/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='path',
            field=models.FileField(upload_to='tracks/'),
        ),
    ]
