# Generated by Django 6.0.5 on 2026-05-21 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_albumauthor_album_alter_albumauthor_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(related_name='albums', through='app.AlbumAuthor', to='app.artist'),
        ),
        migrations.AlterField(
            model_name='albumauthor',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_authors', to='app.album'),
        ),
        migrations.AlterField(
            model_name='albumauthor',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_authors', to='app.artist'),
        ),
    ]
