# Generated by Django 6.0.5 on 2026-05-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_album_artists_alter_albumauthor_album_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artists',
        ),
        migrations.AddField(
            model_name='artist',
            name='albums',
            field=models.ManyToManyField(related_name='artists', through='app.AlbumAuthor', to='app.album'),
        ),
    ]
