# Generated by Django 6.0.5 on 2026-05-15 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_album_cover_artist_cover_alter_track_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='artist',
        ),
    ]
