# Generated by Django 6.0.5 on 2026-05-21 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_album_artists_artist_albums'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='albums',
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(related_name='albums', through='app.AlbumAuthor', to='app.artist'),
        ),
        migrations.AddField(
            model_name='track',
            name='artists',
            field=models.ManyToManyField(related_name='tracks', through='app.TrackAuthor', to='app.artist'),
        ),
        migrations.AlterField(
            model_name='albumauthor',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_albums', to='app.artist'),
        ),
        migrations.AlterField(
            model_name='trackauthor',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_tracks', to='app.artist'),
        ),
        migrations.AlterField(
            model_name='trackauthor',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_authors', to='app.track'),
        ),
    ]
