# Generated by Django 6.0.5 on 2026-05-21 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_artist_albums_album_artists_track_artists_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='users',
            field=models.ManyToManyField(related_name='tracks', through='app.FavoriteTrack', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='albumauthor',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.album'),
        ),
        migrations.AlterField(
            model_name='albumauthor',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.artist'),
        ),
        migrations.AlterField(
            model_name='favoritetrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.track', verbose_name='Трек'),
        ),
        migrations.AlterField(
            model_name='favoritetrack',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='trackauthor',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.artist'),
        ),
        migrations.AlterField(
            model_name='trackauthor',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.track'),
        ),
    ]
