# Generated by Django 6.0.5 on 2026-05-15 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_album_artist_albumfeat_trackfeat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlbumFeat',
            new_name='AlbumAuthor',
        ),
        migrations.RenameModel(
            old_name='TrackFeat',
            new_name='TrackAuthor',
        ),
    ]
