# Generated by Django 6.0.5 on 2026-05-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_albumfeat_albumauthor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
