# Generated by Django 6.0.5 on 2026-05-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_track_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='tracksCount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
