server {
    listen 80;

    # location /static/ {
    #     alias /app/staticfiles/;
    # }
    location / {
        proxy_pass http://backend:8080;
    }
    location /media/ {
        root /app;
        add_header Accept-Ranges bytes;
    }
}